---
- hosts: localhost
  vars:
   host: "10.172.10.1"
   username: "userxx"
   vdom: "root"
   ssl_verify: "False"
  vars_prompt:
  - name: password
    prompt: "Type the password of your fortigate admin account"
    private: no
  tasks:
  - name: Configure interface
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      system_interface:
        name: "vlan_101"
        allowaccess: "ping"
        mode: "static"
        ip: "10.172.101.1/24"
        type: "vlan"
        vlanid: "101"
        role: "lan"
        interface: "switch"
        status: "up"
        vdom: "root"

