---
- hosts: localhost
  vars:
   host: "10.172.10.1"
   username: "userxx"
   vdom: "root"
   ssl_verify: "False"
  vars_prompt:
  - name: password
    prompt: "Type the password of your fortigate admin account"
    private: no.
  tasks:
  - name: Add User Vlan address object
    fortios_firewall_address:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_address:
        name: "vlan_10x address"
        subnet: "10.172.10x.0/24"
        associated_interface: "vlan_10x"
        type: "Interface Subnet"