---
- hosts: localhost
  become: yes
  vars:
    domain: ansible.local
    rev_domain: 0.10.172.10.in-addr.arpa
    subnet: 10.172.10.0
    netmask: 255.255.255.0
    broadcast: 10.172.10.255
    gateway: 10.172.10.1
    rangelow: 10.172.10.100
    rangehigh: 10.172.10.200
    
  tasks:
    # Configure firewall
    # Setup Bind

    - name: Install bind
      yum:
       name: bind
       state: present

    - name: Copy named conf file
      template:
       src: templates/named.conf.j2
       dest: /etc/named.conf
       owner: root
       group: named
       mode: 0660
      notify: restart named

    - name: Make named directory
      file:
       path: /etc/named
       state: directory
       owner: root
       group: named
       mode: 0750

    - name: Copy named conf local file
      template:
       src: templates/named.conf.local.j2
       dest: /etc/named/named.conf.local
       owner: root
       group: named
       mode: 0640
      notify: restart named

    - name: Make zones Directory
      file:
       path: /etc/named/zones
       state: directory
       owner: root
       group: named
       mode: 0750

    - name: Copy forward file
      template:
       src: templates/db.forward.j2
       dest: /etc/named/zones/db.{{ domain }}
       owner: root
       group: named
       mode: 0640
      notify: restart named

    - name: Copy reverse file
      template:
       src: templates/db.reverse.j2
       dest: /etc/named/zones/db.{{ rev_domain }}
       owner: root
       group: named
       mode: 0640
      notify: restart named

    - name: Enable named
      systemd:
       name: named
       enabled: yes

    - name: Open firewall port
      firewalld:
       service: dns
       permanent: true
       state: enabled
       immediate: yes
    
    # Create DHCP server

    - name: Install dhcp
      yum:
       name: dhcp
       state: present

    - name: Open firewall port
      firewalld:
       service: dhcp
       permanent: true
       state: enabled
       immediate: yes

    - name: Copy dhcpd conf local file
      template:
       src: templates/dhcpd.conf.j2
       dest: /etc/dhcp/dhcpd.conf
       owner: root
       group: root
       mode: 0644
      notify: restart dhcpd

    - name: Restart firewalld
      systemd:
       name: firewalld
       enabled: yes
       state: restarted

    - name: Enable dhcpd
      systemd:
       name: dhcpd
       enabled: yes
       state: started

  # Create Ansible Hosts file
    - name: Create Ansible dir
      file:
        path: /etc/ansible
        state: directory
  
    - name: Touch Ansible hosts file
      file:
        path: /etc/ansible/hosts
        state: touch

    - name: Add servers to Ansible hosts file
      blockinfile:
        path: /etc/ansible/hosts
        block: |
          [storage]
          storage.ansible.local
          [esxi]
          esxi.ansible.local
          [vcenter]
          vcenter.ansible.local
          [ansibleserver]
          ansibleserver.ansible.local

    - name: configure network
      shell: |
        nmcli connection modify ens192 ipv4.dns "127.0.0.1"
        shutdown -r +1

  # handlers

  handlers:
    - name: restart named
      service: 
       name: named
       state: restarted

    - name: restart dhcpd
      service: 
       name: dhcpd
       state: restarted